name: Execução dos testes unitários com jest

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v2

      - name: Configura o Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 5.6.0
        
      - name: Instalar dependencias
        run: npm -install
      
      - name: Execultar testes
        run: npm run test